Resources:
  # Define the SNS Topic
  LowestPetrolPriceSNS:
    Type: "AWS::SNS::Topic"
    Properties:
      TopicName: "LowestPetrolPriceNotifications"

  # Define the Lambda execution role
  LambdaExecutionRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "lambda.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Policies:
        - PolicyName: "LambdaExecutionPolicy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                Resource: "arn:aws:logs:*:*:*"
              - Effect: "Allow"
                Action:
                  - "sns:Publish"
                Resource:
                  Ref: "LowestPetrolPriceSNS"

  # Define the Lambda function
  PetrolPriceNotifierLambda:
    Type: "AWS::Lambda::Function"
    Properties:
      FunctionName: "PetrolPriceNotifier"
      Handler: "com.nixonsu.RuntimeHandler"  # Replace with the actual package and handler class
      Role:
        Fn::GetAtt:
          - "LambdaExecutionRole"
          - "Arn"
      Code:
        S3Bucket: "petrol-price-notifier"  # Replace with your S3 bucket name
        S3Key: "petrol-price-notifier-1.0-SNAPSHOT.jar"  # Replace with your jar file path
      Runtime: "java17"
      Timeout: 15
      Environment:
        Variables:
          SNS_TOPIC_ARN: !Ref LowestPetrolPriceSNS

  # Define the EventBridge (CloudWatch Events) rule to trigger the Lambda function
  ScheduledRule:
    Type: "AWS::Events::Rule"
    Properties:
      Description: "Trigger Petrol Price Notifier Lambda every day at 9 AM."
      ScheduleExpression: "cron(0 9 * * ? *)"
      State: "ENABLED"
      Targets:
        -
          Arn:
            Fn::GetAtt:
              - "PetrolPriceNotifierLambda"
              - "Arn"
          Id: "PetrolPriceNotifierLambda"

  # Grant permissions for the EventBridge rule to invoke the Lambda function
  PermissionForEventsToInvokeLambda:
    Type: "AWS::Lambda::Permission"
    Properties:
      FunctionName:
        Ref: "PetrolPriceNotifierLambda"
      Action: "lambda:InvokeFunction"
      Principal: "events.amazonaws.com"
      SourceArn:
        Fn::GetAtt:
          - "ScheduledRule"
          - "Arn"
