name: Petrol Notifier CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - 'README.md'
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    name: 🧪 Run tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'
      - name: Run unit & integration tests
        run: ./gradlew test

#  deploy:
#    name: 🚀 Deploy to production
#    runs-on: ubuntu-latest
#    needs: test
#
#    steps:
#      - uses: actions/checkout@v3
#      - uses: superfly/flyctl-actions/setup-flyctl@master
#      - name: Deploy to fly.io
#        run: ./ops/scripts/deploy.sh
#        env:
#          USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
#          PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
#          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
#          MONGODB_URI: ${{ secrets.MONGODB_URI }}
